#ifndef __AIMESSAGE__
#define __AIMESSAGE__


enum AI_STATE
{
	AI_STATE_NONE,
	AI_WAIT			,AI_MOVE			,AI_ATTACK		,AI_SUPPORT,
	AI_MOVE_NONE	,AI_MOVE_PATROL		,AI_MOVE_MON	,AI_MOVE_PLAYER,	//9
	AI_AT_DISABLE	,AI_AT_CHECK,		AI_AT_ENABLE,
	AI_PLAYER_NONE	,AI_PLAYER_SEARCH	,AI_PLAYER_EXIST,
	AI_EM_NORMAL	,AI_EM_DISCOMPORT	,AI_EM_ANGER,		AI_EM_FURY,			AI_EM_MAD,
	AI_MON_NONE		,AI_MON_SEARCH		,AI_MON_EXIST,
	AI_ACT_NORMAL	,AI_ACT_RUNAWAY		,AI_ACT_COP,
	AI_CON_VERYGOOD	,AI_CON_GOOD		,AI_CON_NORMAL	,AI_CON_CHECK		,AI_CON_BAD,	AI_CON_VERYBAD,		AI_CON_DEAD,
	AI_DEFFENSIVE	,AI_OFFENSIVE,
	AI_HELP_READY	,AI_HELP_ON,
	AI_ASSIST_OFF,	AI_ASSIST_ON		,AI_ASSIST_FAIL,
/////////////////////////////////////////////////////////////////////////////////
	
	AI_EV_DELAY,
	AI_EV_AT_CHECK_DELAY,	AI_EV_AT_CHECK_TRUE,	AI_EV_AT_CHECK_FALSE,
	AI_EV_ATTACK_ENABLE,AI_EV_ATTACK_DISABLE,

	AI_EV_ACT_COP,
	AI_EV_CON_VERYGOOD,AI_EV_CON_GOOD,AI_EV_CON_NORMAL,AI_EV_CON_BAD,AI_EV_CON_VERYBAD,AI_EV_CON_DEAD,
	AI_EV_PLAYER_DEAD,

	
	AI_EV_MV_MON,AI_EV_MV_PLAYER,AI_EV_MV_DONE,
	
	AI_EV_OFFENSIVE,AI_EV_DEFFENSIVE,

	AI_EV_ASSIST_SKILL,
	
	AI_EV_ASSIST_ON,AI_EV_ASSIST_FAIL,

	AI_EV_EM_BAD,AI_EV_EM_GOOD,
	
	AI_EV_ATTACK,
	AI_EV_PLAYER_NONE	,AI_EV_PLAYER_EXIST	,AI_EV_PLAYER_SEARCH,
	AI_EV_MON_NONE	,AI_EV_MON_DELAY	,AI_EV_MON_EXIST,
	AI_EV_HELP
};

#endif

